### Import Data

In [1]:
# import kagglehub

# # Download latest version
# path = kagglehub.dataset_download("aravindpcoder/diabetes-dataset")

# print("Path to dataset files:", path)

### Move Data to Project Folder

In [2]:
# import shutil
# import os

# source_path = r"C:\Users\siver\.cache\kagglehub\datasets\aravindpcoder\diabetes-dataset\versions\1\Dataset of Diabetes .csv"

# destination_dir = os.getcwd()

# shutil.move(source_path, destination_dir)

# print(f"File moved to {destination_dir}")

### Convert data to pandas DataFrame

In [3]:
import pandas as pd

df = pd.read_csv("Dataset of Diabetes .csv")

df.head()

,ID,No_Pation,Gender,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI,CLASS
0,502,17975,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
1,735,34221,M,26,4.5,62,4.9,3.7,1.4,1.1,2.1,0.6,23.0,N
2,420,47975,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
3,680,87656,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
4,504,34223,M,33,7.1,46,4.9,4.9,1.0,0.8,2.0,0.4,21.0,N

### Explore the data

In [4]:
df.shape

(1000, 14)

In [5]:
df.columns

Index(['ID', 'No_Pation', 'Gender', 'AGE', 'Urea', 'Cr', 'HbA1c', 'Chol', 'TG',
       'HDL', 'LDL', 'VLDL', 'BMI', 'CLASS'],
      dtype='object')

In [6]:
df.dtypes

ID             int64
No_Pation      int64
Gender        object
AGE            int64
Urea         float64
Cr             int64
HbA1c        float64
Chol         float64
TG           float64
HDL          float64
LDL          float64
VLDL         float64
BMI          float64
CLASS         object
dtype: object

In [7]:
df.describe()

,ID,No_Pation,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI
count,1000.000000,1.000000e+03,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,340.500000,2.705514e+05,53.528000,5.124743,68.943000,8.281160,4.862820,2.349610,1.204750,2.609790,1.854700,29.578020
std,240.397673,3.380758e+06,8.799241,2.935165,59.984747,2.534003,1.301738,1.401176,0.660414,1.115102,3.663599,4.962388
min,1.000000,1.230000e+02,20.000000,0.500000,6.000000,0.900000,0.000000,0.300000,0.200000,0.300000,0.100000,19.000000
25%,125.750000,2.406375e+04,51.000000,3.700000,48.000000,6.500000,4.000000,1.500000,0.900000,1.800000,0.700000,26.000000
50%,300.500000,3.439550e+04,55.000000,4.600000,60.000000,8.000000,4.800000,2.000000,1.100000,2.500000,0.900000,30.000000
75%,550.250000,4.538425e+04,59.000000,5.700000,73.000000,10.200000,5.600000,2.900000,1.300000,3.300000,1.500000,33.000000
max,800.000000,7.543566e+07,79.000000,38.900000,800.000000,16.000000,10.300000,13.800000,9.900000,9.900000,35.000000,47.750000

In [8]:
df['CLASS'].value_counts()

CLASS
Y     840
N     102
P      53
Y       4
N       1
Name: count, dtype: int64

In [9]:
df = df[df['CLASS'] != 'P']
df

,ID,No_Pation,Gender,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI,CLASS
0,502,17975,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
1,735,34221,M,26,4.5,62,4.9,3.7,1.4,1.1,2.1,0.6,23.0,N
2,420,47975,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
3,680,87656,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
4,504,34223,M,33,7.1,46,4.9,4.9,1.0,0.8,2.0,0.4,21.0,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,200,454317,M,71,11.0,97,7.0,7.5,1.7,1.2,1.8,0.6,30.0,Y
996,671,876534,M,31,3.0,60,12.3,4.1,2.2,0.7,2.4,15.4,37.2,Y
997,669,87654,M,30,7.1,81,6.7,4.1,1.1,1.2,2.4,8.1,27.4,Y
998,99,24004,M,38,5.8,59,6.7,5.3,2.0,1.6,2.9,14.0,40.5,Y
999,248,24054,M,54,5.0,67,6.9,3.8,1.7,1.1,3.0,0.7,33.0,Y

In [10]:
class_mapper = {
    'Y': 1,
    'N': 0
}

df['CLASS'] = df['CLASS'].str.strip() # Remove whitespace

df['CLASS'] = df['CLASS'].replace(class_mapper) # Change to numerical values

df['CLASS'].value_counts()

C:\Users\siver\AppData\Local\Temp\ipykernel_42152\3804890800.py:8: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['CLASS'] = df['CLASS'].replace(class_mapper) # Change to numerical values

CLASS
1    844
0    103
Name: count, dtype: int64

In [ ]:
df = df.drop(columns=['ID', 'No_Pation']) # Drop unneccessary columns

class_col = df.pop('CLASS') # Put target CLASS in first column
df.insert(0, 'CLASS', class_col)

df.head()

   CLASS Gender  AGE  Urea  Cr  HbA1c  Chol   TG  HDL  LDL  VLDL   BMI
0      0      F   50   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5  24.0
1      0      M   26   4.5  62    4.9   3.7  1.4  1.1  2.1   0.6  23.0
2      0      F   50   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5  24.0
3      0      F   50   4.7  46    4.9   4.2  0.9  2.4  1.4   0.5  24.0
4      0      M   33   7.1  46    4.9   4.9  1.0  0.8  2.0   0.4  21.0